apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: bG9jYWxob3N0
  DB_PORT: NTQzMg==
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: dGhyZWVfdGllcl9hcHA=